- hosts: docker-host
  tasks:
    - name: delete old and create new deployment
      shell: kubectl apply -f /opt/deployment.yml ; kubectl delete -f /opt/deployment.yml
    - name: delete old and create new service
      shell: kubetcl apply -f /opt/service.yml ; kubetcl delete -f /opt/service.yml